### PR TITLE
Testing script first attempt by Rachel. 

### PR DESCRIPTION
**Pull request by houtmanr**

### CODE REVIEW

**Comment by smcgregor** [comment]
Looks good to me. @buckinha: Does this look good to you? I think this pulls in some changes you have made subsequently on your fork.

**Comment by buckinha** [comment]
Perfect!

**Comment by smcgregor** [comment]
@buckinha Should I merge this? Which branch of which fork should we all be working from?

**Comment by smcgregor** [comment]
I believe this has already been merged to Hailey's fork, so I am going to close this.

**Pull request closed without merging**
